# Generated by Django 6.0.3 on 2026-04-03 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoPrevisao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_atendimento_id', models.IntegerField()),
                ('produto_id', models.IntegerField()),
                ('defeito_reclamado_id', models.IntegerField(blank=True, null=True)),
                ('defeito_constatado_id', models.IntegerField(blank=True, null=True)),
                ('solucao_id', models.IntegerField(blank=True, null=True)),
                ('data_abertura', models.DateField()),
                ('fabrica_id', models.IntegerField()),
                ('linha_id', models.IntegerField()),
                ('familia_id', models.IntegerField()),
                ('resultado_horas', models.FloatField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Histórico de Previsão',
                'verbose_name_plural': 'Histórico de Previsões',
                'ordering': ['-criado_em'],
            },
        ),
    ]
