# Generated by Django 6.0.3 on 2026-04-19 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('previsao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicoprevisao',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='historicoprevisao',
            name='data_abertura',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicoprevisao',
            name='defeito_constatado_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicoprevisao',
            name='defeito_reclamado_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicoprevisao',
            name='produto_id',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicoprevisao',
            name='solucao_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicoprevisao',
            name='tipo_atendimento_id',
            field=models.IntegerField(db_index=True),
        ),
    ]
